server {
    listen 80;
    listen [::]:80;
    server_name anime.YOUR_DOMAIN;

    location /.well-known/acme-challenge/ {
        root /var/www/acme;
        try_files $uri =404;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name anime.YOUR_DOMAIN;

    ssl_certificate /root/cert/anime.YOUR_DOMAIN/fullchain.pem;
    ssl_certificate_key /root/cert/anime.YOUR_DOMAIN/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers off;

    root /var/www/anime.YOUR_DOMAIN;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~* \.(?:js|css|woff2|png|jpe?g)$ {
        expires 1h;
        add_header Cache-Control "public";
        try_files $uri =404;
    }
}
